name: auth-service

services:
  app:
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME:-"Auth Service"}
      DOMAIN_URL: ${DOMAIN_URL:-http://localhost:8000}

      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES:-1440}

      EMAILS_ENABLED: ${EMAILS_ENABLED:-false}
      SMTP_PORT: ${EMAILS_SMTP_PORT:?}
      SMTP_SERVER: ${EMAILS_SMTP_SERVER:?}
      SMTP_USER: ${EMAILS_SMTP_USER:?}
      SMTP_PASSWORD: ${EMAILS_SMTP_PASSWORD:?}
      FROM_EMAIL: ${EMAILS_FROM_EMAIL:?}
      FROM_NAME: ${EMAILS_FROM_NAME:?}

      USERNAME_MIN_LENGTH: ${USERS_USERNAME_MIN_LENGTH:-3}
      USERNAME_MAX_LENGTH: ${USERS_USERNAME_MAX_LENGTH:-32}
      PASSWORD_MIN_LENGTH: ${USERS_PASSWORD_MIN_LENGTH:-8}
      PASSWORD_MAX_LENGTH: ${USERS_PASSWORD_MAX_LENGTH:-32}

      REDIS_URL: ${REDIS_URL:?}

      MONGO_URI: ${MONGO_URI:?}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME:-auth_server}

    volumes:
      - ./config:/app/config
